---
title: "Capstone Project -- in Progress"
author: "28/10/2018"
output: html_document
---


**Connecting to the AWS Database.**

```{r, message = FALSE}
library(dplyr)
library(ggplot2)
library(tis)
library(stringr)
library(randomForest)

host="[host name here]"
port="[port number here]"
dbname="[dbname here]"
user="[username here]"
password=rstudioapi::askForPassword("Enter your password:")

mr_data = src_mysql(dbname=dbname,host=host,port=port,user=user,password=password)

#[3]
```

**Loading Data to AWS**

```{r}
# Loading the Austin Animal Center Datasets into R
raw_intakes <- read.csv(".../Austin_Animal_Center_Intakes_Oct1.csv", na.strings = c("", "NULL"))# [1]
raw_outcomes <- read.csv(".../Austin_Animal_Center_Outcomes_Oct1.csv", na.strings = c("", "NULL")) # [2]

# Copying Data to the AWS Database
copy_to(mr_data, raw_intakes, temporary = FALSE)
copy_to(mr_data, raw_outcomes, temporary = FALSE)

# Tables in the AWS Database
src_tbls(mr_data)

# Making AWS Tables Accessible in R
intake_data = tbl(mr_data, "raw_intakes")
outcome_data = tbl(mr_data, "raw_outcomes")

```

** Data Cleaning Functions **

```{r}
# where applicable:
## file = 0 is indicative of the intakes dataset.
## file = 1 is indicative of the outcomes dataset.

# Dealing with the DateTime, Date.of.Birth and MonthYear Attributes for the Intakes and Outcomes Datasets.
datetime_converter <- function(date_time, file)
{
  datetime_format = '%m/%d/%Y %I:%M:%S %p'
  date_time$DateTime = as.POSIXct(date_time$DateTime, format = datetime_format)
  date_time$MonthYear = format(as.Date(date_time$DateTime), "%Y-%m")
  
  if(file == 1)
  {
    date_time$Date.of.Birth = as.POSIXct(date_time$Date.of.Birth, format = "%m/%d/%Y")
    date_time$Month = format(as.Date(date_time$DateTime), "%m")
    num_months <- read.delim("/Users/Diana/Documents/Capstone Project/months.txt", header = FALSE)
    names(num_months)[1] <- "Month"
    names(num_months)[2] <- "Outcome.Month"
    date_time$Month <- as.numeric(date_time$Month)
    date_time <- merge(date_time, num_months, by = "Month", all.x = TRUE)
    date_time$Month <- NULL
  }
  
  return(date_time)
}

# Creates a 5 Column DataFrame of the DateTime Values.
datetime_dataframe <- function(input)
{
  datetime_format = '%m/%d/%Y %I:%M:%S %p'
  date_time = data.frame("Full.Entry" = as.POSIXlt(input$DateTime, format = datetime_format))
  date_time$Year = format(date_time$Full.Entry, '%Y')
  date_time$Month = format(date_time$Full.Entry, '%m')
  date_time$Day = format(date_time$Full.Entry, '%d')
  date_time$Time = format(date_time$Full.Entry, '%H:%M:%S')
  
  return(date_time)
}

# Cleans Up the Age.upon.[x] Attributes and Converts the Input to a Unit of Years.
age_cleaning <- function(input, file)
{
  if(file == 0)
  {
    input$Age.upon.Intake = gsub("(1 weeks)", "1 week", input$Age.upon.Intake)
    
    input$Age.upon.Intake[grep("(month)+", input$Age.upon.Intake)] = as.numeric(gsub("(month)+s*", "", input$Age.upon.Intake[grep("(month)+", input$Age.upon.Intake)]))*0.083333545491
    
    input$Age.upon.Intake[grep("(week)+", input$Age.upon.Intake)] = as.numeric(gsub("(week)+s*", "", input$Age.upon.Intake[grep("(week)+", input$Age.upon.Intake)]))*0.01917811
    
    input$Age.upon.Intake[grep("(day)+", input$Age.upon.Intake)] = as.numeric(gsub("(day)+s*", "", input$Age.upon.Intake[grep("(day)+", input$Age.upon.Intake)]))*0.00273973
    
    input$Age.upon.Intake[grep("(year)+", input$Age.upon.Intake)] = as.numeric(gsub("(year)+s*", "", input$Age.upon.Intake[grep("(year)+", input$Age.upon.Intake)]))
    
    input$Age.upon.Intake = sapply(input$Age.upon.Intake, as.numeric)
  }
  
  else
  {
    input$Age.upon.Outcome = gsub("(1 weeks)", "1 week", input$Age.upon.Outcome)
    
    input$Age.upon.Outcome[grep("(month)+", input$Age.upon.Outcome)] = as.numeric(gsub("(month)+s*", "", input$Age.upon.Outcome[grep("(month)+", input$Age.upon.Outcome)]))*0.083333545491
    
    input$Age.upon.Outcome[grep("(week)+", input$Age.upon.Outcome)] = as.numeric(gsub("(week)+s*", "", input$Age.upon.Outcome[grep("(week)+", input$Age.upon.Outcome)]))*0.01917811
    
    input$Age.upon.Outcome[grep("(day)+", input$Age.upon.Outcome)] = as.numeric(gsub("(day)+s*", "", input$Age.upon.Outcome[grep("(day)+", input$Age.upon.Outcome)]))*0.00273973
    
    input$Age.upon.Outcome[grep("(year)+", input$Age.upon.Outcome)] = as.numeric(gsub("(year)+s*", "", input$Age.upon.Outcome[grep("(year)+", input$Age.upon.Outcome)]))
    
    input$Age.upon.Outcome = sapply(input$Age.upon.Outcome, as.numeric)
  }
  
  return(input)
}

# Merging "Unknown" and "<NA>" in the "Sex.Upon.[x]" Attributes.
unknown_sex <- function(input, file)
{
  if(file == 0)
  {
    input$Sex.upon.Intake[is.na(input$Sex.upon.Intake)] = "Unknown"
  }
  
  else
  {
    input$Sex.upon.Outcome[is.na(input$Sex.upon.Outcome)] = "Unknown"
  }
  
  return(input)
}

# Dealing with NAs in the DataFrame.
na_remover <- function(input, file)
{
  if(file == 1)
  {
    input$Name[is.na(input$Name)] <- "No Name"
    input$Outcome.Subtype[is.na(input$Outcome.Subtype)] <- "None"
  }
  
  return(input)
}

# Cleaning the Found.Location Attribute.
edit_location <- function(input, file)
{
  if(file == 0)
  {
    input$Found.Location = gsub("(?:.* in )+", "\\1", input$Found.Location)
  }
  
  return(input)
}

# A Function that Combines the Previous 5 Functions to do a "Total Clean"
total_clean <- function(input, file)
{
  input = datetime_converter(input, file)
  input = age_cleaning(input, file)
  input = unknown_sex(input, file)
  input = na_remover(input, file)
  input = edit_location(input,file)
  
  return(input)
}

# This Function Creates a New Attribute -- Days.to.Outcome.
## Days.to.Outcome tells the user how many days an animal remained at the center.
days_to_outcome <- function(input)
{
  input$Days.to.Outcome = as.double(difftime(input$Outcome.Date, input$Intake.Date, units = "days"))
  
  return(input)
}

inner_join_func <- function(intakes, outcomes)
{
  # Preparing for Inner Join #
  intakes = subset(intakes, select = -Animal.Type)
  
  ## Renaming 2 Columns in Each Dataset.
  names(intakes)[2] = "Intake.Date"
  names(intakes)[3] = "Intake.MonthYear"
  names(outcomes)[3] = "Outcome.Date"
  names(outcomes)[4] = "Outcome.MonthYear"
  
  # Performing the Inner Join #
  total = outcomes %>% inner_join(intakes, by = c("Animal.ID" = "Animal.ID")) %>% filter((Outcome.Date - Intake.Date) > 0)
  
  ## Adding a New Column to Describe the Number of Days the Animal Stayed in the Shelter.
  total = days_to_outcome(total)
  
  ## Cleaning Superfluous Rows Resulting from the Join.
  total = total %>% select(everything()) %>% group_by(Animal.ID, Outcome.Date) %>% filter(which.min(Days.to.Outcome) == row_number())
  
  return(total)
}
```


** Feature Engineering & Other Model Preparation Functions **

```{r}
# Creating New Breed Attributes -- Purebred.or.Mixed and AKC.Group
dog_breed_cleaning <- function(input)
{
  # Loading in Text Files that Dictate AKC Dog Group
  sporting.group <- read.delim(".../sporting_group.txt", header = FALSE)
  herding.group <- read.delim(".../herding_group.txt", header = FALSE)
  hound.group <- read.delim(".../hound_group.txt", header = FALSE)
  nonsporting.group <- read.delim(".../nonsporting_group.txt", header = FALSE)
  terrier.group <- read.delim(".../terrier_group.txt", header = FALSE)
  toy.group <- read.delim(".../toy_group.txt", header = FALSE)
  working.group <- read.delim(".../working_group.txt", header = FALSE)
  misc.class <- read.delim(".../miscellaneous_class.txt", header = FALSE)
  fss.group <- read.delim(".../fss_group.txt", header = FALSE)
  
  # Editing the Text Files
  akc_groups <- rbind(sporting.group, herding.group, hound.group, nonsporting.group, terrier.group, toy.group, working.group, misc.class, fss.group)
  
  names(akc_groups)[1] = "Breed"
  names(akc_groups)[2] = "AKC.Group"
  
  # Altering the Breed Attribute.
  input$Breed = gsub("(Span)+(?!iel)", "Spaniel", input$Breed, perl = TRUE)
  input$Breed = gsub("(Bruss+)(?!els)", "Brussels", input$Breed, perl = TRUE)
  input$Breed = gsub("(Retr+)(?!iever)", "Retriever", input$Breed, perl = TRUE)
  input$Breed = gsub("(Chesa+)(?!peake)", "Chesapeake", input$Breed, perl = TRUE)
  input$Breed = gsub("(Pinsch+)(?!er)", "Pinscher", input$Breed, perl = TRUE)
  input$Breed = gsub("(Rhod+)(?!esian)", "Rhodesian", input$Breed, perl = TRUE)
  input$Breed = gsub("(Anatol+)(?!ian)", "Anatolian", input$Breed, perl = TRUE)
  input$Breed = gsub("(Terr+)(?!ier)", "Terrier", input$Breed, perl = TRUE)
  input$Breed = gsub("(Eng+)(?!lish)", "English", input$Breed, perl = TRUE)
  input$Breed = gsub("(Spanielish+)", "Spanish", input$Breed, perl = TRUE)
  
  # Adding the Attributes
  ## Purebred.or.Mixed
  input$Purebred.or.Mixed <- NA
  input$Purebred.or.Mixed[grepl("(Mix)+", input$Breed) | grepl("/", input$Breed)] = "Mixed"
  input$Purebred.or.Mixed[!grepl("(Mix)+", input$Breed) & !grepl("/", input$Breed)] = "Purebred"
  
  ## AKC.Group
  input <- merge(input, akc_groups, by = "Breed", all.x = TRUE)
  input$AKC.Group <- as.character(input$AKC.Group)
  input$AKC.Group[is.na(input$AKC.Group)] <- "Not Recognized"
  
  return(input)
}

# Creating New Breed Attributes for Cats -- Purebred.or.Mixed
cat_breed_cleaning <- function(input)
{
  # Adding the Attributes
  ## Purebred.or.Mixed
  input$Purebred.or.Mixed <- NA
  input$Purebred.or.Mixed[grepl("(Mix)+", input$Breed) | grepl("/", input$Breed)] = "Mixed"
  input$Purebred.or.Mixed[!grepl("(Mix)+", input$Breed) & !grepl("/", input$Breed)] = "Purebred"
  
  return(input)
}

# Creating a General Color Attribute.
animal_color <- function(input, type)
{
  if(type == "Cat")
  {
    cat_colors <- read.delim(".../cat_colors.txt", header = FALSE, stringsAsFactors = FALSE)
    colors <- sapply(cat_colors$V1, function(color) grepl(color, input$Color))
    
    input$Color <- gsub("Torbie", "Tortie", input$Color)
    input$Gen.Color <- apply(colors, 1, function(x) paste0(names(x)[x], collapse = "/"))
    input$Gen.Color[input$Gen.Color == ""] <- input$Color[input$Gen.Color == ""]
    input$Gen.Color[grepl("/", input$Gen.Color) | grepl("Tricolor", input$Gen.Color)] = "Multicolored"
  }
  
  else if(type == "Dog")
  {
    dog_colors <- read.delim(".../dog_colors.txt", header = FALSE, stringsAsFactors = FALSE)
    colors <- sapply(dog_colors$V1, function(color) grepl(color, input$Color))
    
    input$Gen.Color <- apply(colors, 1, function(x) paste0(names(x)[x], collapse = "/"))
    input$Gen.Color[input$Gen.Color == ""] <- input$Color[input$Gen.Color == ""]
    input$Gen.Color[grepl("/", input$Gen.Color) | grepl("Tricolor", input$Gen.Color)] = "Multicolored"
  }
  
  else if(type == "Bird")
  {
    input$Gen.Color <- input$Color
    input$Gen.Color[grepl("/", input$Gen.Color) | grepl("Tricolor", input$Gen.Color)] = "Multicolored"
  }
  
  return(input)
}

# Creating a Gender Attribute.
animal_gender <- function(input)
{
  input$Gender <- NA
  input$Gender[grepl("(Male)+", input$Sex.upon.Outcome)] = "Male"
  input$Gender[grepl("(Female)+", input$Sex.upon.Outcome)] = "Female"
  input$Gender[grepl("(Unknown)+", input$Sex.upon.Outcome)] = "Unknown"
  
  return(input)
}

# Creating an Attribute that Indicates if Sex.upon.Intake differs from Sex.upon.Outcome.
sex_difference <- function(input)
{
  input$Sex.Difference[which(input$Sex.upon.Intake != input$Sex.upon.Outcome)] <- gsub("( Female| Male)*", "", input$Sex.upon.Outcome[which(input$Sex.upon.Intake != input$Sex.upon.Outcome)])
  input$Sex.Difference[which(input$Sex.upon.Intake == input$Sex.upon.Outcome)] <- "None"
  
  return(input)
}

# A Function that Calls All Feature Engineering Functions
feature_engineering <- function(input, type)
{
  input = animal_gender(input)
  input = sex_difference(input)
  
  if(type == "Dog")
  {
    input = dog_breed_cleaning(input)
    input = animal_color(input,type)
  }
  
  else if(type == "Cat")
  {
    input = cat_breed_cleaning(input)
    input = animal_color(input, type)
  }
  
  else if(type == "Bird")
  {
    input = animal_color(input, type)
  }
  
  return(input)
}

# Splitting the Data into Training and Test Sets.
train_test <- function(dataset)
{
  index <- nrow(dataset)
  sizes <- round(index*0.7)
  filtered_index <- sample(1:index, sizes)
  
  train_set <- dataset[filtered_index,]
  test_set <- dataset[-filtered_index,]
  
  return(list(train_set, test_set))
}

```


** Initial Data Exploration **

```{r}
# Bringing the Relevant Data from AWS to Memory.
dog_intakes = intake_data %>% select(-one_of("Name", "Breed", "Color")) %>% filter(Animal.Type == "Dog") %>% collect()

dog_outcomes = outcome_data %>% select(everything()) %>% filter(Animal.Type == "Dog" & !is.na(Age.upon.Outcome) & !is.na(Outcome.Type)) %>% collect()

## Cleaning Datasets.
dog_intakes = total_clean(dog_intakes, 0)
dog_outcomes = total_clean(dog_outcomes, 1)

## Performing the Inner Join.
dog_total = inner_join_func(dog_intakes, dog_outcomes)

# Applying Feature Engineering Functions.
dog_total <- feature_engineering(dog_total)
```


### Works Cited
[1] https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Intakes/wter-evkm

[2] https://data.austintexas.gov/Health-and-Community-Services/Austin-Animal-Center-Outcomes/9t4d-g238

[3] https://datascience-enthusiast.com/R/AWS_RDS_R_Python.html
